### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by strum3nt** [openlawnz/openlawnz-web#1]
add logo

**Comment by williamparry** [comment]
Can you upload the logo here

**Comment by strum3nt** [comment]
![openlaw-logo](https://user-images.githubusercontent.com/3869728/38593564-08549546-3d96-11e8-8b4f-5c80e6b390a4.jpg)

![openlaw-logo](https://user-images.githubusercontent.com/3869728/38593566-08b7b7ac-3d96-11e8-8f15-464e2eb1caf6.png)

**Comment by williamparry** [comment]
Have you got the favicon and [Chrome Extension images](https://developer.chrome.com/webstore/images)? We can also reuse it for the Github project image.

**Comment by strum3nt** [comment]
![chrome-ext-logo](https://user-images.githubusercontent.com/3869728/38648982-42e5e23e-3e48-11e8-94e3-e1462bf6e9a5.png)

**Comment by strum3nt** [comment]
![page 11 1](https://user-images.githubusercontent.com/3869728/38649023-73f2fca4-3e48-11e8-9dde-8add30e23dad.png)
