### ISSUE TITLE
Build Advanced Search

### ISSUE THREAD

**Issue by caionnx** [openlawnz/openlawnz-web#106]

**Comment by caionnx** [comment]
Progress on branch feature/advanced-search

**Comment by Tzhong16** [comment]
👌

**Comment by alex-h-k** [comment]
Will check it after work. Thanks Caio

**Comment by strum3nt** [comment]
On the advanced search UI, can we add the interface to support the search APIs described here:

https://github.com/openlawnz/openlawnz-web/issues/106

(In other words, add options in the advanced search field selector for case_text, citation, cited by, and cites)

**Comment by caionnx** [comment]
@strum3nt as I have some time now and this was simple I made it. Pull the changes on `feature/advanced-search`. Just remember that the API need to be changed as well for processing those new parameters.
