### ISSUE TITLE
Build architecture of Profile page 

### ISSUE THREAD

**Issue by caionnx** [openlawnz/openlawnz-web#109]
Refer to "Profile - V2.2 - Profile Folder View V1.0"
https://www.figma.com/file/uREYEHFZ58vYHfJaCfVAs9/OpenLaw-Website?node-id=1671%3A2

**Comment by Tzhong16** [comment]
Hello Caio, please give me the access to drag the 'To do' to 'In prograss' in Case Folders , links here:https://github.com/orgs/openlawnz/projects/1#card-28909804      Thanks

**Comment by caionnx** [comment]
Hey Terence, permission granted can you try again, please? Thanks

**Comment by Tzhong16** [comment]
Hey Caio, still can't drag it into 'In prograss'. But, I will start to build it with Nicola. Thanks.

**Comment by caionnx** [comment]
I'll check with Will later, moved for you. Thanks.
