### ISSUE TITLE
Add a Service Worker?

### ISSUE THREAD

**Issue by airbr** [openlawnz/openlawnz-web#158]
I have some limited experience adding service workers in the past but I have no idea how to do it within this React framework.

The service worker would provide the ability to display a custom offline page as its most basic usage. They have a bunch of other uses as well, like pro active cacheing, but again I dont know how this conflicts with the existing framework. 

https://developers.google.com/web/fundamentals/primers/service-workers

**Comment by airbr** [comment]
I just tested around and got a basic service worker installing that serves a fall back page if the internet is down, if that is something that would be of interest to the group/project

**Comment by williamparry** [comment]
Is there something else the service worker could be used for?

**Comment by miinow** [comment]
You may get what you want to know about service worker with React from the project which can be created by create-react-app, the route would be /src/serviceWorker.js

**Comment by caionnx** [comment]
With service workers would be a good step moving towards of becoming a PWA.

This could be a task after we integrate Gatsby. They have specific plugins for service-workers capability https://www.gatsbyjs.org/docs/add-offline-support-with-a-service-worker/

On a first impression the challenge appears to be handle authentication offline and data so the user can search something.
