### ISSUE TITLE
Change Adobe PDF Viewer plugin to In-Line mode

### ISSUE THREAD

**Issue by caionnx** [openlawnz/openlawnz-web#172]
The widget is implemented in the `SingleCaseView` component currently as `Full Window` mode in the development branch.

- Demo of this embed mode: https://documentcloud.adobe.com/view-sdk-demo/index.html
- Official documentation: https://www.adobe.io/apis/documentcloud/dcsdk/docs.html

**Comment by caionnx** [comment]
@williamparry @strum3nt 

I got this one to analyze it, and I noticed that if we change to In-Line mode we'll lose the capability of adding notes to the PDF. The library don't allow the feature in this mode.
Once we have auth0 up and running, the ability to add a sticky note, highlight text and drawing in it associated with the user would be amazing.

Should we continue with this task?

**Comment by strum3nt** [comment]
Yeah I think absolutely still worth it - but user could change view mode perhaps? Have a button to switch between inline (no comments) and full (comments). With a badge saying how many comments there are maybe?

Andrew
