### ISSUE TITLE
scroll to top of search results on selection of new page in pagination

### ISSUE THREAD

**Issue by strum3nt** [openlawnz/openlawnz-web#174]
Current behaviour leaves page scroll in place when clicking through to (for example) page 2 from page 1

Should scroll to top of search results for the new page

**Comment by arghac14** [comment]
@strum3nt can I work on this?

**Comment by strum3nt** [comment]
Sure thing :)

**Comment by strum3nt** [comment]
I think https://github.com/openlawnz/openlawnz-web/pull/218 linked
