### ISSUE TITLE
Link to official legislation site from case info tab

### ISSUE THREAD

**Issue by strum3nt** [openlawnz/openlawnz-web#202]
On cases that have legislation references (visible in the info tab) the links to sections of legislation should be clickable links.

For example:
![image](https://user-images.githubusercontent.com/3869728/73711909-49008680-476d-11ea-8ab7-b6e81bf48827.png)

District Courts Act should link to this page: http://legislation.govt.nz/act/public/1947/0016/latest/DLM242776.html?search=ad_act______200_ac%40bn%40rn%40dn%40apub%40rpub%40rimp_ac%40ainf%40anif%40arep%40rinf%40rnif_a_aw_se&p=2

Legislation URL can be found using the [OpenLaw API](https://api.openlaw.nz/graphiql)

```query MyQuery {
  legislationTitle(_title: "District Courts Act 1947") {
    link
  }
}
```

Append the result to http://legislation.govt.nz/ to generate the full URL. 

A further enhancement would be to link directly to the **section** referenced not just the full Act but as yet there does not seem to be an easy way to determine a section URL.

**Comment by strum3nt** [comment]
Parliamentary Counsel Office has kindly explained a method by which a **section** URL can be determined by reusing the URL on the results page of an advanced search.

EG an advanced search for section 1 of the Holidays Act 2003 has this construct:

```http://www.legislation.govt.nz/act/results.aspx?search=ad_act__holidays+act+2003___1_25_ac%40bn%40rn%40dn%40apub%40aloc%40apri%40apro%40aimp%40bgov%40bloc%40bpri%40bmem%40rpub%40rimp_ac%40ainf%40anif%40aaif%40aase%40arep%40bcur%40rinf%40rnif_a_aw_se&p=1```

The link on the results page is:

```http://www.legislation.govt.nz/act/public/2003/0129/latest/link.aspx?search=ad_act__holidays+act+2003___1_25_ac%40bn%40rn%40dn%40apub%40aloc%40apri%40apro%40aimp%40bgov%40bloc%40bpri%40bmem%40rpub%40rimp_ac%40ainf%40anif%40aaif%40aase%40arep%40bcur%40rinf%40rnif_a_aw_se&p=1 ```

Or use year/number:
```http://www.legislation.govt.nz/act/results.aspx?search=ad_act___2003_129_1_25_ac%40bn%40rn%40dn%40apub%40aloc%40apri%40apro%40aimp%40bgov%40bloc%40bpri%40bmem%40rpub%40rimp_ac%40ainf%40anif%40aaif%40aase%40arep%40bcur%40rinf%40rnif_a_aw_se&p=1```

To get:

```http://www.legislation.govt.nz/act/public/2003/0129/latest/link.aspx?search=ad_act___2003_129_1_25_ac%40bn%40rn%40dn%40apub%40aloc%40apri%40apro%40aimp%40bgov%40bloc%40bpri%40bmem%40rpub%40rimp_ac%40ainf%40anif%40aaif%40aase%40arep%40bcur%40rinf%40rnif_a_aw_se&p=1 ```

So you can use the following constructs to be taken directly to a section:

```http://www.legislation.govt.nz/[leg type/[doc type]/[year]/[number]/latest/link.aspx?search=ad_[leg type]__[act+title]___[section number]_25_ac%40bn%40rn%40dn%40apub%40aloc%40apri%40apro%40aimp%40bgov%40bloc%40bpri%40bmem%40rpub%40rimp_ac%40ainf%40anif%40aaif%40aase%40arep%40bcur%40rinf%40rnif_a_aw_se&p=1```

```http://www.legislation.govt.nz/[leg type/[doc type]/[year]/[number]/latest/link.aspx?search=ad_[leg type]___[year]_[number]_[section number]_25_ac%40bn%40rn%40dn%40apub%40aloc%40apri%40apro%40aimp%40bgov%40bloc%40bpri%40bmem%40rpub%40rimp_ac%40ainf%40anif%40aaif%40aase%40arep%40bcur%40rinf%40rnif_a_aw_se&p=1```

**Comment by gwkim8107** [comment]
Hi Andrew, I am trying to reproduction for this issue, but I have a problem that I can't fetch any data within my local environment. Can you give any idea for this problem?
