### ISSUE TITLE
Fix header and footer layout on some pages

### ISSUE THREAD

**Issue by dlouise64** [openlawnz/openlawnz-web#205]
Some pages are not using the `<Layout />` component, `<SEO />` component and do not have a header or footer. These need to be added to:

- Plugins
- Developers
- News
- Login
- Search
- SingleCase
- SingleNews

Take a look at pages/about.js as a guide.

pages filenames need to be lower case i.e
about.js
developers.js

branch from here:
https://github.com/openlawnz/openlawnz-web/pull/190

**Comment by gwkim8107** [comment]
'gatsby develop' command has failed again. The error message like below.
 
**ERROR** 

gatsby <develop> can only be run for a gatsby site.
Either the current working directory does not contain a valid package.json or 'gatsby' is not specified as a dependency
