### ISSUE TITLE
Migrate About page to Gatsby/NetlifyCMS

### ISSUE THREAD

**Issue by williamparry** [openlawnz/openlawnz-web#229]

**Comment by Tzhong16** [comment]
Hello Will, any description or instruction how to do this migration? Thanks

**Comment by williamparry** [comment]
Sure:

- [Example implementation](https://github.com/openlawnz/openlawnz-web/blob/master/src/pages/index.js#L46)
- [Example config](https://github.com/openlawnz/openlawnz-web/blob/master/static/admin/config.yml)
- [Netlify CMS](https://www.netlifycms.org/docs/intro/)
- [README](https://github.com/openlawnz/openlawnz-web#running-the-cms)

**Comment by gwkim8107** [comment]
How can I assign me for this issue? I might be lost permission.
