### ISSUE TITLE
Update website

### ISSUE THREAD

**Issue by williamparry** [openlawnz/openlawnz-web#4]
https://github.com/openlawnz/openlawnz-web/issues/3
https://github.com/openlawnz/openlawnz-web/issues/2
https://github.com/openlawnz/openlawnz-web/issues/1

**Comment by williamparry** [comment]
It's swapping the current logo to be SVG rather than png https://github.com/openlawnz/openlawnz-web/blob/master/openlaw-logo.svg (and putting the SVG in the right location)

**Comment by pmg1991** [comment]
@williamparry  #1 also done

**Comment by williamparry** [comment]
Cool, can you submit a pull request?

**Comment by pmg1991** [comment]
@williamparry  yes pull request raised. #7

**Comment by pmg1991** [comment]
One last thing you can remove all extra favicon files because favicons-webpack-plugin builds all the 37 different icons for iOS devices, Android devices and the Desktop browser out of your my-logo.png. I've used logo-small.png for this for now.
