### ISSUE TITLE
Listbox ui improvements

### ISSUE THREAD

**Issue by Neozaru** [openlawnz/openlawnz-web#447]
The listbox component - used in Advanced Search - can be improved :
- Text in each list element to be left-aligned instead of centered.
- Text hightligh covering entire list element when hovering.
- List elements to be separated more clearly.

![image](https://user-images.githubusercontent.com/1905292/82267654-1a778600-99c1-11ea-8016-c640eed26ccb.png)

**Comment by BenRauzi** [comment]
Thanks for your contribution. This has now made it's way to master :)
