### ISSUE TITLE
Reduce padding when on mobile

### ISSUE THREAD

**Issue by williamparry** [openlawnz/openlawnz-web#64]
e.g. 
![image](https://user-images.githubusercontent.com/348091/66166490-d080a080-e67a-11e9-9555-b0200b856be1.png)

**Comment by Areadrill** [comment]
Hi! I can take this issue.

**Comment by KarlaChen** [comment]
Hi, @williamparry . Can I do it?

**Comment by Areadrill** [comment]
Can I get a bit more info on this issue? Do you want to reduce the gutter padding (the one between the centered content and the edges of the screen), or something else?

**Comment by williamparry** [comment]
@KarlaChen  @Areadrill  It's the spacing either side of the search box.

**Comment by Danielrhodesy** [comment]
So something more like this? To match the box below?

<img width="313" alt="Screen Shot 2019-11-21 at 3 41 40 PM" src="https://user-images.githubusercontent.com/37157488/69299550-ab211380-0c75-11ea-9723-c7b953921a0a.png">

**Comment by Danielrhodesy** [comment]
Or the spacing on the top and bottom?

<img width="312" alt="Screen Shot 2019-11-22 at 9 36 00 AM" src="https://user-images.githubusercontent.com/37157488/69374749-9e4eff00-0d0b-11ea-9404-219dc966b7d2.png">

**Comment by caionnx** [comment]
Top and bottom, just keep the same proportion.

**Comment by caionnx** [comment]
Hi @Danielrhodesy any impediments in this one? Thanks
