### ISSUE TITLE
Add multilingual support

### ISSUE THREAD

**Issue by williamparry** [openlawnz/openlawnz-web#77]
@caionnx could you advise on this?

**Comment by ZeroSoulEater** [comment]
I would take a look at this

**Comment by caionnx** [comment]
Hi @ZeroSoulEater, at the first moment we were thinking of using [react-intl](https://github.com/formatjs/react-intl). What are your thoughts on the matter?

**Comment by ZeroSoulEater** [comment]
I like i18next they also have a [react](https://react.i18next.com) version :)

**Comment by williamparry** [comment]
@ZeroSoulEater thank you for your comment - I think it's best we step back and scope this a bit more first before we continue on, so I'm closing for now.
